# ! d2 first-person.d2 ../png/first-person.png

direction: right

classes: {
  text: {shape: text}
}

ǣm̐/æ̃ː: {class: text}
m̐ǣm̐/ ̃æ̃ː: {class: text}
nǣm̐/n̪æ̃ː: {class: text}
nǣn/n̪æːn̪: {class: text}
nān/n̪ɑːn̪: {class: text}
ñān/ɲɑːn̪: {class: text}
nān/n̪ɑːn̪ + u: {class: text}
nānu/n̪ɑːn̪u: {class: text}
nēn/n̪eːn̪: {class: text}
nēn/n̪eːn̪ + u: {class: text}
nēnu/n̪eːn̪u: {class: text}
nǣ/n̪æː: {class: text}
nā/nɑː: {class: text}
nē/n̪eː: {class: text}
ǣn/æːn̪: {class: text}
ān/ɑːn̪: {class: text}
ān/ɑːn̪ + u: {class: text}
ānu/ɑːn̪u: {class: text}
ēn/eːn̪: {class: text}
ēn + ŭ/eːn̪ + ɯ: {class: text}
ēnŭ/eːn̪ɯ: {class: text}
ēn/eːn̪ + u: {class: text}
ēnu/eːn̪u: {class: text}
yān/jɑːn̪: {class: text}
yān + ŭ/jɑːn̪ + ɯ: {class: text}
yānŭ/jɑːn̪ɯ: {class: text}
ǣ/æː: {class: text}
ē/eː: {class: text}

ǣm̐/æ̃ː -> m̐ǣm̐/ ̃æ̃ː
m̐ǣm̐/ ̃æ̃ː -> nǣm̐/n̪æ̃ː
nǣm̐/n̪æ̃ː -> nǣn/n̪æːn̪
nǣn/n̪æːn̪ -> nān/n̪ɑːn̪
nān/n̪ɑːn̪ -> ñān/ɲɑːn̪
nān/n̪ɑːn̪ -> nān/n̪ɑːn̪ + u
nān/n̪ɑːn̪ + u -> nānu/n̪ɑːn̪u
nǣn/n̪æːn̪ -> nēn/n̪eːn̪
nēn/n̪eːn̪ -> nēn/n̪eːn̪ + u
nēn/n̪eːn̪ + u -> nēnu/n̪eːn̪u
nǣm̐/n̪æ̃ː -> nǣ/n̪æː
nǣ/n̪æː -> nā/nɑː
nǣ/n̪æː -> nē/n̪eː

ǣm̐/æ̃ː -> ǣn/æːn̪
ǣn/æːn̪ -> ān/ɑːn̪
ān/ɑːn̪ -> ān/ɑːn̪ + u
ān/ɑːn̪ + u -> ānu/ɑːn̪u
ǣn/æːn̪ -> ēn/eːn̪
ēn/eːn̪ -> ēn + ŭ/eːn̪ + ɯ
ēn + ŭ/eːn̪ + ɯ -> ēnŭ/eːn̪ɯ
ēn/eːn̪ -> ēn/eːn̪ + u
ēn/eːn̪ + u -> ēnu/eːn̪u
ǣn/æːn̪ -> yān/jɑːn̪
yān/jɑːn̪ -> yān + ŭ/jɑːn̪ + ɯ
yān + ŭ/jɑːn̪ + ɯ -> yānŭ/jɑːn̪ɯ
ǣm̐/æ̃ː -> ǣ/æː
ǣ/æː -> ē/eː
