# ! d2 interrogative.d2 ../png/interrogative.png

direction: right

classes: {
  text: {shape: text}
}

ǣm̐/æ̃ː: {class: text}
ēm̐/ẽː: {class: text}
ēn/eːn̪: {class: text}
ēn/eːn̪ + u: {class: text}
ēnu/eːn̪u: {class: text}
ēm/eːm: {class: text}
ēm + i/eːm + ɪ: {class: text}
ēmi/eːmɪ: {class: text}
yām̐/jɑ̃ː: {class: text}
yām̐ + am̐/jɑ̃ː + ə̃: {class: text}
yāvam̐/jɑːʋə̃: {class: text}
yāvan/jɑːʋən̪: {class: text}
yāvan/jɑːʋən̪ + u: {class: text}
yāvanu/jɑːʋən̪u: {class: text}
ām̐/ɑ̃ː: {class: text}
ām̐ + udu/ɑ̃ː + ud̪u: {class: text}
āvudu/ɑːʋud̪u: {class: text}
ōm̐/õː: {class: text}
ōm̐/õː + u: {class: text}
ōvu/õːʋu: {class: text}
ōm̐ + a/õː + ə: {class: text}
ō + a/oː + ə: {class: text}
vā: {class: text}

ǣm̐/æ̃ː -> ēm̐/ẽː
ēm̐/ẽː -> ēn/eːn̪
ēn/eːn̪ -> ēn/eːn̪ + u
ēn/eːn̪ + u -> ēnu/eːn̪u
ēm̐/ẽː -> ēm/eːm
ēm/eːm -> ēm + i/eːm + ɪ
ēm + i/eːm + ɪ -> ēmi/eːmɪ
ǣm̐/æ̃ː -> yām̐/jɑ̃ː
yām̐/jɑ̃ː -> yām̐ + am̐/jɑ̃ː + ə̃
yām̐ + am̐/jɑ̃ː + ə̃ -> yāvam̐/jɑːʋə̃
yāvam̐/jɑːʋə̃ -> yāvan/jɑːʋən̪
yāvan/jɑːʋən̪ -> yāvan/jɑːʋən̪ + u
yāvan/jɑːʋən̪ + u -> yāvanu/jɑːʋən̪u
ǣm̐/æ̃ː -> ām̐/ɑ̃ː
ām̐/ɑ̃ː -> ām̐ + udu/ɑ̃ː + ud̪u
ām̐ + udu/ɑ̃ː + ud̪u -> āvudu/ɑːʋud̪u
ām̐/ɑ̃ː -> ōm̐/õː
ōm̐/õː -> ōm̐/õː + u
ōm̐/õː + u -> ōvu/õːʋu
ōm̐/õː -> ōm̐ + a/õː + ə
ōm̐ + a/õː + ə -> ō + a/oː + ə
ō + a/oː + ə -> vā
