# ! d2 skeptical-emphasising.d2 ../png/skeptical-emphasising.png

direction: right

classes: {
  text: {shape: text}
}

ǣm̐/æ̃ː: {class: text}
ēm̐/ẽː: {class: text}
ē/eː: {class: text}
ām̐/ɑ̃ː: {class: text}
ā/ɑ̃ː: {class: text}
ōm̐/õː: {class: text}
ō/oː: {class: text}

ǣm̐/æ̃ː -> ēm̐/ẽː
ēm̐/ẽː -> ē/eː
ǣm̐/æ̃ː -> ām̐/ɑ̃ː
ām̐/ɑ̃ː -> ā/ɑ̃ː
ām̐/ɑ̃ː -> ōm̐/õː
ōm̐/õː -> ō/oː
