# ! d2 ಉತ್ತಮಪುರುಷ.d2 ../png/ಉತ್ತಮಪುರುಷ.png

direction: right

classes: {
  text: {shape: text}
}

ಏ್ಁ: {class: text}
ಀಏ್ಁ: {class: text}
ನೇ್ಁ: {class: text}
ನೇ್ಁ: {class: text}
ನೇ್ನ್: {class: text}
ನಾನ್: {class: text}
ಞಾನ್: {class: text}
ನಾನ್ + ಉ: {class: text}
ನಾನು: {class: text}
ನೇನ್: {class: text}
ನೇನ್ + ಉ: {class: text}
ನೇನು: {class: text}
ನೇ್: {class: text}
ನಾ: {class: text}
ನೇ: {class: text}
ಏ್‍ನ್: {class: text}
ಆನ್: {class: text}
ಆನ್ + ಉ: {class: text}
ಆನು: {class: text}
ಏನ್: {class: text}
ಏನ್ + ಉ್: {class: text}
ಏನು್: {class: text}
ಏನ್ + ಉ: {class: text}
ಏನು: {class: text}
ಯಾನ್: {class: text}
ಯಾನ್ + ಉ್: {class: text}
ಯಾನು್: {class: text}
ಏ್: {class: text}
ಏ: {class: text}

ಏ್ಁ -> ಀಏ್ಁ
ಀಏ್ಁ -> ನೇ್ಁ
ನೇ್ಁ -> ನೇ್ನ್
ನೇ್ನ್ -> ನಾನ್
ನಾನ್ -> ಞಾನ್
ನಾನ್ -> ನಾನ್ + ಉ
ನಾನ್ + ಉ -> ನಾನು
ನೇ್ನ್ -> ನೇನ್
ನೇನ್ -> ನೇನ್ + ಉ
ನೇನ್ + ಉ -> ನೇನು
ನೇ್ಁ -> ನೇ್
ನೇ್ -> ನಾ
ನೇ್ -> ನೇ

ಏ್ಁ -> ಏ್‍ನ್
ಏ್‍ನ್ -> ಆನ್
ಆನ್ -> ಆನ್ + ಉ
ಆನ್ + ಉ -> ಆನು
ಏ್‍ನ್ -> ಏನ್
ಏನ್ -> ಏನ್ + ಉ್
ಏನ್ + ಉ್ -> ಏನು್
ಏನ್ -> ಏನ್ + ಉ
ಏನ್ + ಉ -> ಏನು
ಏ್‍ನ್ -> ಯಾನ್
ಯಾನ್ -> ಯಾನ್ + ಉ್
ಯಾನ್ + ಉ್ -> ಯಾನು್
ಏ್ಁ -> ಏ್
ಏ್ -> ಏ
