# ! d2 ಪ್ರಶ್ನಾರ್ಥಕ.d2 ../png/ಪ್ರಶ್ನಾರ್ಥಕ.png

direction: right

classes: {
  text: {shape: text}
}

ಏ್ಁ: {class: text}
ಏಁ: {class: text}
ಏನ್: {class: text}
ಏನ್ + ಉ: {class: text}
ಏನು: {class: text}
ಏಮ್: {class: text}
ಏಮ್ + ಇ: {class: text}
ಏಮಿ: {class: text}
ಯಾಁ: {class: text}
ಯಾಁ + ಅಁ: {class: text}
ಯಾವಁ: {class: text}
ಯಾವನ್: {class: text}
ಯಾವನ್ + ಉ: {class: text}
ಯಾವನು: {class: text}
ಆಁ: {class: text}
ಆಁ + ಉದು: {class: text}
ಆವುದು: {class: text}
ಓಁ: {class: text}
ಓಁ + ಉ: {class: text}
ಓವು: {class: text}
ಓಁ + ಅ: {class: text}
ಓ + ಅ: {class: text}
ವಾ: {class: text}

ಏ್ಁ -> ಏಁ
ಏಁ -> ಏನ್
ಏನ್ -> ಏನ್ + ಉ
ಏನ್ + ಉ -> ಏನು
ಏಁ -> ಏಮ್
ಏಮ್ -> ಏಮ್ + ಇ
ಏಮ್ + ಇ -> ಏಮಿ
ಏ್ಁ -> ಯಾಁ
ಯಾಁ -> ಯಾಁ + ಅಁ
ಯಾಁ + ಅಁ -> ಯಾವಁ
ಯಾವಁ -> ಯಾವನ್
ಯಾವನ್ -> ಯಾವನ್ + ಉ
ಯಾವನ್ + ಉ -> ಯಾವನು
ಏ್ಁ -> ಆಁ
ಆಁ -> ಆಁ + ಉದು
ಆಁ + ಉದು -> ಆವುದು
ಆಁ -> ಓಁ
ಓಁ -> ಓಁ + ಉ
ಓಁ + ಉ -> ಓವು
ಓಁ -> ಓಁ + ಅ
ಓಁ + ಅ -> ಓ + ಅ
ಓ + ಅ -> ವಾ
