# ! d2 ಪ್ರಶ್ನಾರ್ಥಕ-ಎಲ್ಲ.d2 ../png/ಪ್ರಶ್ನಾರ್ಥಕ-ಎಲ್ಲ.png

direction: down

classes {
  text: {shape: text}
  bold: {
    shape: text
    style: {
      bold: true
      font-size: 24
    }
  }
  node: {
    shape: oval
    style: {
      bold: true
      font-size: 24
    }
  }
  highlight: {
    shape: oval
    style: { fill: lightgreen }
    label: ""
  }
  plhighlight: {
    shape: oval
    style: { fill: mediumaquamarine }
    label: ""
  }
  nv: { label: "ಬಲವಾದ (ಅರ್ಧ)ಅನುಸ್ವಾರದಿಂದ ಮೊದಲೂ ನಕಾರವುಂಟಾಗಿದೆ" }
  vn: { label: "(ಅರ್ಧ)ಅನುಸ್ವಾರ > ಸ್ವರದನಂತರ ನಕಾರ" }
  vm: { label: "(ಅರ್ಧ)ಅನುಸ್ವಾರ > ಸ್ವರದನಂತರ ಮಕಾರ" }
  vv: { label: "(ಅರ್ಧ)ಅನುಸ್ವಾರ > ಸ್ವರದನಂತರ (ಮಕಾರದ ಮೂಲಕ?) ವಕಾರ" }
  ǣā: { label: "ಏ್ > ಆ"}
  ǣē: { label: "ಏ್ > ಏ"}
  ǣyā: { label: "ಏ್ > ಯಾ"}
  āō: { label: "ಆ > ಓ"}
  u: { label: "+ ಉ"}
  ŭ: { label: "+ ಉ್"}
  i: { label: "+ ಇ"}
  a: { label: "ಸಂಬಂಧಾರ್ಥಕ, ಗುಣವಾಚಕ + ಅ"}
  an: { label: "ಏಕವಚನ ಪುಲ್ಲಿಂಗವಾಚಕ + ಅಁ"}
  aḷ: { label: "ಏಕವಚನ ಸ್ತ್ರೀಲಿಂಗವಾಚಕ + ಅಳ್"}
  ar: { label: "ಬಹುವಚನ ಪುಂಸ್ತ್ರೀಲಿಂಗವಾಚಕ + ಅರ್"}
  udu: {label: "ಏಕವಚನ ನಪುಂಸಕಲಿಂಗ + ಉದು"}
  adu: {label: "ಏಕವಚನ ನಪುಂಸಕಲಿಂಗ + ಅದು"}
  adŭ: {label: "ಏಕವಚನ ನಪುಂಸಕಲಿಂಗ + ಅದು್"}
  vu: {label: "ಏಕವಚನ ನಪುಂಸಕಲಿಂಗ + ವು"}
  d: {label: "ಏಕವಚನ ನಪುಂಸಕಲಿಂಗ + ದ್"}
  dŭ: {label: "ಏಕವಚನ ನಪುಂಸಕಲಿಂಗ + ದು್"}
  v0: {label: "(ಅರ್ಧ)ಅನುಸ್ವಾರಲೋಪ"}
  æa: {label: "ಎ್ > ಅ"}
  æe: {label: "ಎ್ > ಎ"}
  nd: {label: "ನ್ > ದ್"}
}

ಎ್ಁ {
  class: node
  label: ""

  ಎ್ಁ {class: bold}
  "ಪ್ರಶ್ನಾರ್ಥಕದ ಮೂಲ (ಏರುಕಾಕುವಿನೊಂದಿಗೆ)" {class: text}
}

ಏ್ಁ {
  class: node
  _.ಎ್ಁ -> _.ಏ್ಁ: "ಪ್ರತ್ಯಯವಿರದಾಗ ದೀರ್ಘ"
}

ಏಁ {
  class: node
  _.ಏ್ಁ -> _.ಏಁ {class: ǣē}
}

ಏನ್ {
  class: highlight
  ಏನ್ {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ: ಹಳಗನ್ನಡ" {class: text}
  _.ಏಁ -> _.ಏನ್ {class: vn}
}

ಏನು {
  class: highlight
  ಏನು {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ: ಕನ್ನಡ" {class: text}
  _.ಏನ್ -> _.ಏನು {class: u}
}

ಏಮ್ {
  class: node
  _.ಏಁ -> _.ಏಮ್ {class: vm}
}

ಏಮಿ {
  class: highlight
  ಏಮಿ {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ: ತೆಲುಗು" {class: text}
  _.ಏಮ್ -> _.ಏಮಿ {class: i}
}

ಏವ್ {
  class: node
  _.ಏ್ಁ -> _.ಏವ್ {class: vv}
}

ಏವಁ {
  class: node
  _.ಏವ್ -> _.ಏವಁ {class: an}
}

ಏವನ್ {
  class: highlight
  ಏವನ್ {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ಪುಲ್ಲಿಂಗ: ತಮಿಳು, ಮಲಯಾಳ" {class: text}
  _.ಏವಁ -> _.ಏವನ್ {class: vn}
}

ಏವಳ್ {
  class: highlight
  ಏವಳ್ {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ಸ್ತ್ರೀಲಿಂಗ: ತಮಿಳು, ಮಲಯಾಳ" {class: text}
  _.ಏವ್ -> _.ಏವಳ್ {class: aḷ}
}

ಏವರ್ {
  class: plhighlight
  ಏವರ್ {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ಪುಂಸ್ತ್ರೀಲಿಂಗ: ಮಲಯಾಳ" {class: text}
  _.ಏವ್ -> _.ಏವರ್ {class: ar}
}

ಏ {
  class: highlight
  ಏ {class: bold}
  a: |`
    - ಗುಣವಾಚಕ, ನಿರ್ದೇಶನಾರ್ಥಕ: ತೆಲುಗು, ಕೊಲಮಿ
    - ಪ್ರಶ್ನಾರ್ಥಕ, ಸಂದೇಹಾರ್ಥಕ ಪ್ರತ್ಯಯ: ಕನ್ನಡ
  `| {class: text}
  _.ಏಁ -> _.ಏ {class: v0}
}

ಏದ್ {
  class: highlight
  ಏದ್ {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ನಪುಂಸಕಲಿಂಗ: ಪಾರ್ಜಿ" {class: text}
  _.ಏ -> _.ಏದ್ {class: d}
}

ಏದು್ {
  class: highlight
  ಏದು್ {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ನಪುಂಸಕಲಿಂಗ: ತಮಿಳು, ಮಲಯಾಳ" {class: text}
  _.ಏದ್ -> _.ಏದು್ {class: ŭ}

}

ಏರ್ {
  class: node
  _.ಏ -> _.ಏರ್ {class: ar}
}

ಏರು್ {
  class: highlight
  ಏರು್ {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ಪುಂಸ್ತ್ರೀಲಿಂಗ: ತುಳು" {class: text}
  _.ಏರ್ -> _.ಏರು್ {class: ŭ}
}

ಯಾಁ {
  class: node
  _.ಏ್ಁ -> _.ಯಾಁ {class: ǣyā}
}

ಯಾವ್ {
  class: node
  _.ಯಾಁ -> _.ಯಾವ್ {class: vv}
}

ಯಾವಁ {
  class: node
  _.ಯಾವ್ -> _.ಯಾವಁ {class: an}
}

ಯಾವನ್ {
  class: highlight
  ಯಾವನ್ {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ಪುಲ್ಲಿಂಗ: ತಮಿಳು, ಮಲಯಾಳ" {class: text}
  _.ಯಾವಁ -> _.ಯಾವನ್ {class: vn}
}

ಯಾವನು {
  class: highlight
  ಯಾವನು {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ಪುಲ್ಲಿಂಗ: ಕನ್ನಡ" {class: text}
  _.ಯಾವನ್ -> _.ಯಾವನು {class: u}
}

ಯಾವಳ್ {
  class: highlight
  ಯಾವಳ್ {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ಸ್ತ್ರೀಲಿಂಗ: ತಮಿಳು, ಮಲಯಾಳ" {class: text}
  _.ಯಾವ್ -> _.ಯಾವಳ್ {class: aḷ}
}

ಯಾವಳು {
  class: highlight
  ಯಾವಳು {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ಸ್ತ್ರೀಲಿಂಗ: ಕನ್ನಡ" {class: text}
  _.ಯಾವಳ್ -> _.ಯಾವಳು {class: u}
}

ಯಾವುದು {
  class: highlight
  ಯಾವುದು {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ನಪುಂಸಕಲಿಂಗ: ಕನ್ನಡ" {class: text}
  _.ಯಾವ್ -> _.ಯಾವುದು {class: udu}
}

ಯಾವದು {
  class: highlight
  ಯಾವದು {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ನಪುಂಸಕಲಿಂಗ: ಕನ್ನಡ" {class: text}
  _.ಯಾವ್ -> _.ಯಾವದು {class: adu}
}

ಯಾವದು್ {
  class: highlight
  ಯಾವದು್ {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ನಪುಂಸಕಲಿಂಗ: ತಮಿಳು" {class: text}
  _.ಯಾವ್ -> _.ಯಾವದು್ {class: adŭ}
}

ಯಾವರ್ {
  class: plhighlight
  ಯಾವರ್ {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ಪುಂಸ್ತ್ರೀಲಿಂಗ: ತಮಿಳು, ಮಲಯಾಳ" {class: text}
  _.ಯಾವ್ -> _.ಯಾವರ್ {class: ar}
}

ಯಾ {
  class: highlight
  ಯಾ {class: bold}
  "ಗುಣವಾಚಕ, ನಿರ್ದೇಶನಾರ್ಥಕ: ಕನ್ನಡ, ತಮಿಳು" {class: text}
  _.ಯಾಁ -> _.ಯಾ {class: v0}
}

ಯಾರ್ {
  class: plhighlight
  ಯಾರ್ {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ಪುಂಸ್ತ್ರೀಲಿಂಗ: ತಮಿಳು" {class: text}
  _.ಯಾ -> _.ಯಾರ್ {class: ar}
}

ಯಾರು {
  class: plhighlight
  ಯಾರು {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ಪುಂಸ್ತ್ರೀಲಿಂಗ: ಕನ್ನಡ" {class: text}
  _.ಯಾರ್ -> _.ಯಾರು {class: u}
}

ಯಾದ್ {
  class: node
  _.ಯಾ -> _.ಯಾದ್ {class: d}
}

ಯಾದು್ {
  class: highlight
  ಯಾದು್ {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ನಪುಂಸಕಲಿಂಗ: ತಮಿಳು, ಮಲಯಾಳ" {class: text}
  _.ಯಾದ್ -> _.ಯಾದು್ {class: ŭ}
}

ಆಁ {
  class: node
  _.ಏ್ಁ -> _.ಆಁ {class: ǣā}
}

ಆವ್ {
  class: node
  _.ಆಁ -> _.ಆವ್ {class: vv}
}

ಆವಁ {
  class: node
  _.ಆವ್ -> _.ಆವಁ {class: an}
}

ಆವನ್ {
  class: node
  _.ಆವಁ -> _.ಆವನ್ {class: vn}
}

ಆವನು {
  class: highlight
  ಆವನು {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ಪುಲ್ಲಿಂಗ: ಹಳಗನ್ನಡ" {class: text}
  _.ಆವನ್ -> _.ಆವನು {class: u}
}

ಆವಳ್ {
  class: node
  _.ಆವ್ -> _.ಆವಳ್ {class: aḷ}
}

ಆವಳು {
  class: highlight
  ಆವಳು {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ಸ್ತ್ರೀಲಿಂಗ: ಹಳಗನ್ನಡ" {class: text}
  _.ಆವಳ್ -> _.ಆವಳು {class: u}
}

ಆವುದು {
  class: highlight
  ಆವುದು {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ನಪುಂಸಕಲಿಂಗ: ಹಳಗನ್ನಡ" {class: text}
  _.ಆವ್ -> _.ಆವುದು {class: udu}
}

ಆವರ್ {
  class: plhighlight
  ಆವರ್ {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ಪುಂಸ್ತ್ರೀಲಿಂಗ: ತಮಿಳು" {class: text}
  _.ಆವ್ -> _.ಆವರ್ {class: ar}
}

ಆರ್ {
  class: plhighlight
  ಆರ್ {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ಪುಂಸ್ತ್ರೀಲಿಂಗ: ಹಳಗನ್ನಡ, ತಮಿಳು" {class: text}
  _.ಆ -> _.ಆರ್ {class: ar}
}

ಆರು {
  class: plhighlight
  ಆರು {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ಪುಂಸ್ತ್ರೀಲಿಂಗ: ಹಳಗನ್ನಡ" {class: text}
  _.ಆರ್ -> _.ಆರು {class: u}
}

ಆರು್ {
  class: plhighlight
  ಆರು್ {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ಪುಂಸ್ತ್ರೀಲಿಂಗ: ಕೊಡವ" {class: text}
  _.ಆರ್ -> _.ಆರು್ {class: ŭ}
}

ಆ {
  class: highlight
  ಆ {class: bold}
  "ಪ್ರಶ್ನಾರ್ಥಕ, ಸಂದೇಹಾರ್ಥಕ ಪ್ರತ್ಯಯ: ಕನ್ನಡ, ತುಳು, ತಮಿಳು" {class: text}
  _.ಆಁ -> _.ಆ {class: v0}
}

ಓಁ {
  class: node
  _.ಆಁ -> _.ಓಁ {class: āō}
}

ಓವ್ {
  class: node
  _.ಓಁ -> _.ಓವ್ {class: vv}
}

ಓವು {
  class: highlight
  ಓವು {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ನಪುಂಸಕಲಿಂಗ: ತುಳು" {class: text}
  _.ಓವ್ -> _.ಓವು {class: vu}
}

ಓ {
  class: highlight
  ಓ {class: bold}
  "ಪ್ರಶ್ನಾರ್ಥಕ, ಸಂದೇಹಾರ್ಥಕ ಪ್ರತ್ಯಯ: ಕನ್ನಡ, ತುಳು, ತಮಿಳು" {class: text}
  _.ಓಁ -> _.ಓ {class: v0}
}

ವಾ {
  class: highlight
  ವಾ {class: bold}
  "ಗುಣವಾಚಕ, ನಿರ್ದೇಶನಾರ್ಥಕ: ತುಳು" {class: text}
  _.ಓ -> _.ವಾ {class: a}
}

ಎಁ {
  class: node
  _.ಎ್ಁ -> _.ಎಁ {class: æe}
}

ಎವ್ {
  class: node
  _.ಎಁ -> _.ಎವ್ {class: vv}
}

ಎವಁ {
  class: node
  _.ಎವ್ -> _.ಎವಁ {class: an}
}

ಎವನ್ {
  class: highlight
  ಎವನ್ {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ಪುಲ್ಲಿಂಗ: ತಮಿಳು" {class: text}
  _.ಎವಁ -> _.ಎವನ್ {class: vn}
}

ಎವಳ್ {
  class: highlight
  ಎವಳ್ {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ಸ್ತ್ರೀಲಿಂಗ: ತಮಿಳು" {class: text}
  _.ಎವ್ -> _.ಎವಳ್ {class: aḷ}
}

ಎವು {
  class: highlight
  ಎವು {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ನಪುಂಸಕಲಿಂಗ: ತುಳು" {class: text}
  _.ಎವ್ -> _.ಎವು {class: vu}
}

ಎವರ್ {
  class: plhighlight
  ಎವರ್ {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ಪುಂಸ್ತ್ರೀಲಿಂಗ: ತಮಿಳು" {class: text}
  _.ಎವ್ -> _.ಎವರ್ {class: ar}
}

ಎ {
  class: node
  _.ಎಁ -> _.ಎ {class: v0}
}

ಎದ್ {
  class: node
  _.ಎ -> _.ಎದ್ {class: d}
}

ಎದು್ {
  class: highlight
  ಎದು್ {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ನಪುಂಸಕಲಿಂಗ: ತಮಿಳು" {class: text}
  _.ಎದ್ -> _.ಎದು್ {class: ŭ}
}

ಎದು {
  class: highlight
  ಎದು {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ನಪುಂಸಕಲಿಂಗ: ಕನ್ನಡ" {class: text}
  _.ಎದ್ -> _.ಎದು {class: u}
}

ನೇ್ಁ {
  class: node
  _.ಏ್ಁ -> _.ನೇ್ಁ {class: nv}
}

ನೇಁ {
  class: node
  _.ನೇ್ಁ -> _.ನೇಁ {class: ǣē}
}

ನೇ {
  class: plhighlight
  ನೇ {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ಪುಂಸ್ತ್ರೀಲಿಂಗ: ಕುರಕ್" {class: text}
  _.ನೇಁ -> _.ನೇ {class: v0}
}

ನೇರ್ {
  class: node
  _.ನೇ -> _.ನೇರ್ {class: ar}
}

ದೇರ್ {
  class: plhighlight
  ದೇರ್ {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ಪುಂಸ್ತ್ರೀಲಿಂಗ: ಬ್ರಾಹುಯಿ" {class: text}
  _.ನೇರ್ -> _.ದೇರ್ {class: nd}
}

ದೇ {
  class: plhighlight
  ದೇ {class: bold}
  "ಪ್ರಥಮಾವಿಭಕ್ತಿ ಪುಂಸ್ತ್ರೀಲಿಂಗ: ಬ್ರಾಹುಯ್" {class: text}
  _.ನೇ -> _.ದೇ {class: nd}
}
