# ! d2 ಸಂದೇಹಾರ್ಥಕ-ಅವಧಾರಣಾರ್ಥಕ.d2 ../png/ಸಂದೇಹಾರ್ಥಕ-ಅವಧಾರಣಾರ್ಥಕ.png

direction: right

classes: {
  text: {shape: text}
}

ಏ್ಁ: {class: text}
ಏಁ: {class: text}
ಏ: {class: text}
ಆಁ: {class: text}
ಆ: {class: text}
ಓಁ: {class: text}
ಓ: {class: text}

ಏ್ಁ -> ಏಁ
ಏಁ -> ಏ
ಏ್ಁ -> ಆಁ
ಆಁ -> ಆ
ಆಁ -> ಓಁ
ಓಁ -> ಓ
